# Site settings
title:          DOGSEAR
description:    "Jinjoo's log"
baseurl:        "/"
url:            "https://jinjoochoi.github.io"

# Author
author:
  name:         "Jinjoo Choi"
  email:        "jinjoooooooo@gmail.com"
  github_username: jinjoochoi
  url:            "https://jinjoochoi.github.io"


# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

collections:
  films:
    output: true
    permalink: /films/:name

defaults:
  - scope:
      path: ""
      type: "films"
    values:
      layout: film

g-analytics: UA-115470668-1
