# Site settings
title:          DOGSEAR
description:    "Jinjoo's log"
baseurl:        "/"
url:            "https://jinjoochoi.github.io"

# Author
author:
  name:         "Jinjoo Choi"
  email:        "jinjoooooooo@gmail.com"
  github_username: jinjoochoi
  url:            "https://jinjoochoi.github.io"


# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  - jekyll-paginate-multiple

# Permalink
permalink:      /:year-:month-:day/:title


# Pagination
paginate_multiple:
  - paginate: 5
    paginate_path: "/page:num/"
    sub_dir: '/post'
  - paginate: 12
    paginate_path: '/film/page:num/'
    sub_dir: '/film'

# Collections
collections:
  film:
    output: true

# Analytics
g-analytics: UA-115470668-1
